'use client';

import { ThemeProvider } from './components/theme-provider';
import localFont from 'next/font/local';
import './globals.css';
import { ModeToggle } from './toggle/page';


import Image from 'next/image';

// Load the local fonts with variables
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// Metadata (if needed)
 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <marquee> </marquee>
        {/* Wrap with ThemeProvider */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
         
          </ThemeProvider>
          
          <ModeToggle/>

    
          
          {children}

       
     
        
      </body>
    </html>
  );
}
